### ISSUE TITLE
HTML poznámky

### ISSUE THREAD

**Issue by zladkaskazkina** [JavaBorka/cv-koderka#1]
Jak jsme se bavili s Lud'kem, v headeru bych použila H1 s elementem "span".
Dále bych používala nadpisy úrovně H2, maximálně H3.

**Comment by zladkaskazkina** [comment]
U navigaci bych použila místo "ul" spíš "nav"

**Comment by JavaBorka** [comment]
Ahoj Vladi, ďěkuji za zpětnou vazbu. 

- změnila jsem hlavní nadpis na h1 a zbytek na h2.
- povedlo se mi přidat obrázek v sekci školy
- každému datumu jsem odstranila zvýraznění
- navigaci jsem chtěla prohodit z ul na nav, ale kompletně se mi rozhodily styly a už jsem neměla síly to piplat, tak jsem to nechala v tom seznamu.

Barča

**Comment by zladkaskazkina** [comment]
Děkuji! vypadá to fajn
